### ISSUE TITLE
TaskNotCompletedException thrown on every client disconnect

### ISSUE THREAD

**Issue by Callisto95** [Karan-Gandhi/Java-Networking-Library#1]
title says everything

caused by Context, line 101:

fix:
if(!tasks.isEmpty()) {
	throw new TaskNotCompletedException(currentTask);
}

**Comment by Callisto95** [comment]
I should clarify, that I used the removeClient method as specified in the documentation and yet the exception was still thrown
I also just guessed what the solution is and how to deal with it.

**Comment by Karan-Gandhi** [comment]
Thank you so much for bringing that out! Apparently that was also causing a bunch of exceptions to be raised when you stop the server.
